# Netlify configuration for Simply Business Tracker
# This file configures the deployment settings for production

[build]
  # Build command - this will be run on Netlify's servers
  command = "npm ci && npx expo export --platform web --output-dir dist --clear"
  
  # Directory to publish - where the built files are located
  publish = "dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# SPA routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets for 1 year
[[headers]]
  for = "/_expo/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts for 1 year
[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images for 1 month
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Development preview settings
[context.deploy-preview]
  command = "npm ci && npx expo export --platform web --output-dir dist --clear"

[context.branch-deploy]
  command = "npm ci && npx expo export --platform web --output-dir dist --clear"

# Form handling (if needed in the future)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
